# Generated by Django 3.1.1 on 2020-10-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_unit', models.CharField(max_length=10)),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=50)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.products')),
                ('super_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.supermarket')),
            ],
        ),
    ]
